### ISSUE TITLE
4.0 beta upgrade error

### ISSUE THREAD

**Issue by aspark21** [gjb2048/moodle-format_grid#164]
Hi Gareth,

Saw a 4.0 beta is out so have tried upgrade but have encountered the following error:

```
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 149216 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 201208 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 207303 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 216420 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 223373 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215646 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215646 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215646 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215648 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215648 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215649 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215655 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215655 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 215655 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 451659 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 672632 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 694630 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 238281 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 236958 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 242987 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 242987 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 244148 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 244148 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 244148 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 244148 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 244148 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 358497 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 358499 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 244363 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 245191 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 249874 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 249874 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 249874 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92 
Notice: Undefined offset: 249874 in /path/to/moodle/course/format/grid/db/upgrade.php on line 92
Cannot create file 678884/format_grid/sectionimage/255413/goi_keyword-research.jpg

[More information about this error](http://docs.moodle.org/400/en/error/moodle/storedfilenotcreated)

Debug info: Duplicate entry '180ee1cbaf44ca975821c176e5064cc0f16dbe21' for key 'mdl_file_pat_uix'
INSERT INTO mdl_files (contenthash,pathnamehash,contextid,component,filearea,itemid,filepath,filename,userid,filesize,mimetype,status,source,author,license,timecreated,timemodified,sortorder,referencefileid) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => 'f748da160a373c779fe6526d017a8984acdb456a',
1 => '180ee1cbaf44ca975821c176e5064cc0f16dbe21',
2 => 678884,
3 => 'format_grid',
4 => 'sectionimage',
5 => '255413',
6 => '/',
7 => 'goi_keyword-research.jpg',
8 => '2',
9 => '499067',
10 => 'image/jpeg',
11 => '0',
12 => NULL,
13 => NULL,
14 => NULL,
15 => '1523022406',
16 => '1523022406',
17 => '0',
18 => NULL,
)]
Error code: storedfilenotcreated×Dismiss this notification
Stack trace:
line 1199 of /lib/filestorage/file_storage.php: stored_file_creation_exception thrown
line 100 of /course/format/grid/db/upgrade.php: call to file_storage->create_file_from_storedfile()
line 709 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()
×Dismiss this notification
```

Ran it again just to be sure, got a different error but similarly failed.

```
Error writing to database

[More information about this error](http://docs.moodle.org/400/en/error/moodle/dmlwriteexception)

Debug info: Duplicate entry '149128' for key 'mdl_formgridimag_sec_uix'
INSERT INTO mdl_format_grid_image (sectionid,courseid,image,displayedimagestate) VALUES(?,?,?,?)
[array (
0 => '149128',
1 => '8990',
2 => 'goi_Contacts (1).png',
3 => 0,
)]
Error code: dmlwriteexception×Dismiss this notification
Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 72 of /course/format/grid/db/upgrade.php: call to mysqli_native_moodle_database->insert_record()
line 709 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()
```

**Comment by gjb2048** [comment]
Thanks for the pre-release report @aspark21 - I think this can happen when a course section image exists that's used for the summary or is left over from old logic flaw and the image no longer exists in the 'format_grid_icon' table.

**Comment by gjb2048** [comment]
@aspark21 https://github.com/gjb2048/moodle-format_grid/commit/b064c4f3efe973548a3676b6b95ab16ef4cf4534 Should fix the issue.  Difficult for me to test fully due to the complexities of getting a test environment to that point on a hunch.

**Comment by rimacher** [comment]
Hi,
I'm getting the same error but the fix didn't solve the issue.

**Comment by gjb2048** [comment]
>
> Despite the error, do the course images restore as expected?  And can I
have an export of the files table filtered on course section please.

**Comment by gjb2048** [comment]
And what error exactly as the code has changed please?

**Comment by rimacher** [comment]
Error writing to database

[More information about this error](http://docs.moodle.org/400/en/error/moodle/dmlwriteexception)
Debug info: Duplicate entry '8430' for key 'mdl_formgridimag_sec_uix'
INSERT INTO mdl_format_grid_image (sectionid,courseid,image,displayedimagestate) VALUES(?,?,?,?)
[array (
0 => '8430',
1 => '1',
2 => '300px-Biological_cell_svg.png',
3 => 0,
)]
Error code: dmlwriteexception
Stack trace:

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
    line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 72 of /course/format/grid/db/upgrade.php: call to mysqli_native_moodle_database->insert_record()
    line 709 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
    line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
    line 719 of /admin/index.php: call to upgrade_noncore()

**Comment by gjb2048** [comment]
Thanks, in that case I really need an export of your format_grid_icon (the
old table) as there are duplicates for some reason and that shouldn't
happen.

**Comment by rimacher** [comment]
Do you need an export of the entire format_grid_icon table?

**Comment by gjb2048** [comment]
Yes please Rima, as you should not have duplicates on sectionid - see the
M3.11 XML definition file.

**Comment by rimacher** [comment]
[mdl_format_grid_icon.csv](https://github.com/gjb2048/moodle-format_grid/files/9439320/mdl_format_grid_icon.csv)

**Comment by gjb2048** [comment]
Thanks, humm, thinking about it, could be course restore before upgrade
issue and entries already exist.

**Comment by gjb2048** [comment]
@rimacher Thanks for that, the CSV file doesn't show a duplicate, this means that somehow the courses are being restored and the data is already there... which is really odd as an in-place upgrade would have the courses already in place and this upgrade script would cope with that scenario.  How are you doing the upgrade / what procedure are you using / what are the steps please?

**Comment by rimacher** [comment]
I'm using a test server with Moodle 4.0.2+ (Build: 20220714) that has a previous version of the grid format 3.11.1.1 (2021102701).

I updated the grid directory directly on the server and got the error while preforming the upgrade.

**Comment by gjb2048** [comment]
@rimacher Ok, but what procedure did you follow to upgrade Moodle core please?

**Comment by yedidiaklein** [comment]
> @rimacher Ok, but what procedure did you follow to upgrade Moodle core please?

The Moodle core was upgraded using upgrade.php cli

**Comment by gjb2048** [comment]
@rimacher Ok, that's the actual upgrade on the machine, but what steps / human procedure did you follow please?  i.e. I replaced the files...

**Comment by gjb2048** [comment]
@rimacher And had you previously downgraded and run the script again?

**Comment by gjb2048** [comment]
@rimacher Ok, spent an hour or so creating a new M3.11 test install, installed Grid for M3.11, restored a test course, upgraded core (via UI), then upgraded Grid (via UI) and cannot replicate!

**Comment by gjb2048** [comment]
@rimacher Also... in your test CSV file, the problem entry is for course '1', but that's normally the 'site course' set to 'format_site' and why does that course have '569' sections?

**Comment by gjb2048** [comment]
@rimacher Please supply the information requested.  But I'm starting to think you sent me on a Wild Goose Chase with data / processes (human) that established a situation that in reality could not happen, please demonstrate this is not the case.

**Comment by gjb2048** [comment]
Duplicate format_grid_image issue reported here too: https://moodle.org/mod/forum/discuss.php?d=437697#p1762506 - not making sense!

**Comment by gjb2048** [comment]
@rimacher Please, please can I have more information as requested on this as its driving me nuts!  No logic can currently explain why it is happening for you.

**Comment by gjb2048** [comment]
@rimacher Does the issue occur if you update via the UI?  Why are you not getting back to be after over a week?  I'm trying to sort this and yet I can't help you if you don't help me.

**Comment by gjb2048** [comment]
Ok, did an update from M3.9 to M4.0 and used the CLI (on Windows with MINGW64) and still cannot replicate.

**Comment by rimacher** [comment]
Unfortunately I don't have enough technical knowledge to provide this information. I didn't upgrade the moodle core, only the plugins.

**Comment by gjb2048** [comment]
@rimacher Ok, but what 'human' process did you follow?  What exact steps did you undertake please?

**Comment by gjb2048** [comment]
@rimacher Surely you can tell me if you ran the update twice?

**Comment by rimacher** [comment]
I first tried upgrading using the official plugin release, I believe it was 4.0.0.1
I got an error, so I wanted to open a ticket. I saw that a fix is available and tried using it to upgrade again, still got an error.
So yes, I tried upgrading twice.

**Comment by gjb2048** [comment]
@rimacher Thanks, so the first time, what did you do?  Put Moodle in maintenance mode etc?  What steps did you perform please?

**Comment by rimacher** [comment]
It's a test system so no maintenance mode or any other changes. I placed the new plugin folder on the server and tried upgrading using the browser interface.

**Comment by gjb2048** [comment]
@rimacher Thanks, so what happened to the old code for the format?  Was it removed before you put the code on?

**Comment by gjb2048** [comment]
@rimacher I need to know each step please, i.e. like detailed here: https://github.com/gjb2048/moodle-format_grid#upgrade-instructions

**Comment by rimacher** [comment]
The old folder was removed before I put the new one.

**Comment by gjb2048** [comment]
@rimacher Thank you.

**Comment by gjb2048** [comment]
@rimacher What database engine are you using please?

**Comment by gjb2048** [comment]
And @rimacher, what OS with version are you running please?

**Comment by rimacher** [comment]
It's linux and mariadb (I don't know the versions).

**Comment by gjb2048** [comment]
@rimacher Ok, login to Moodle and look at the 'Environment' and 'PHP info' pages under the 'Server' section of 'Site administration' please.  I need to know if its specific to that.

**Comment by gjb2048** [comment]
Note, worked out and can replicate:

```
Debug info: Duplicate entry '180ee1cbaf44ca975821c176e5064cc0f16dbe21' for key 'mdl_file_pat_uix'
INSERT INTO mdl_files (contenthash,pathnamehash,contextid,component,filearea,itemid,filepath,filename,userid,filesize,mimetype,status,source,author,license,timecreated,timemodified,sortorder,referencefileid) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => 'f748da160a373c779fe6526d017a8984acdb456a',
1 => '180ee1cbaf44ca975821c176e5064cc0f16dbe21',
2 => 678884,
3 => 'format_grid',
4 => 'sectionimage',
5 => '255413',
6 => '/',
7 => 'goi_keyword-research.jpg',
8 => '2',
9 => '499067',
10 => 'image/jpeg',
11 => '0',
12 => NULL,
13 => NULL,
14 => NULL,
15 => '1523022406',
16 => '1523022406',
17 => '0',
18 => NULL,
)]
Error code: storedfilenotcreated×Dismiss this notification
Stack trace:
line 1199 of /lib/filestorage/file_storage.php: stored_file_creation_exception thrown
line 100 of /course/format/grid/db/upgrade.php: call to file_storage->create_file_from_storedfile()
line 709 of /lib/upgradelib.php: call to xmldb_format_grid_upgrade()
line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()
×Dismiss this notification
```

but not the sectionid issue.

**Comment by gjb2048** [comment]
I.e:

Cannot create file 25/format_grid/sectionimage/2/goi_43124.jpg

More information about this error
Debug info: Duplicate entry 'e01c0a94ff2326133ff6ff631894915b7878b4a7' for key 'mdl_files.mdl_file_pat_uix'
INSERT INTO mdl_files (contenthash,pathnamehash,contextid,component,filearea,itemid,filepath,filename,userid,filesize,mimetype,status,source,author,license,timecreated,timemodified,sortorder,referencefileid) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
[array (
0 => '3949b871eb3ddd5e66ffa030c5d232cc3bbb5c3d',
1 => 'e01c0a94ff2326133ff6ff631894915b7878b4a7',
2 => 25,
3 => 'format_grid',
4 => 'sectionimage',
5 => '2',
6 => '/',
7 => 'goi_43124.jpg',
8 => NULL,
9 => '582117',
10 => 'image/jpeg',
11 => '0',
12 => NULL,
13 => NULL,
14 => NULL,
15 => '1662466529',
16 => '1662466529',
17 => '0',
18 => NULL,
)]
Error code: storedfilenotcreated
Stack trace:

    line 1199 of \lib\filestorage\file_storage.php: stored_file_creation_exception thrown
    line 110 of \course\format\grid\db\upgrade.php: call to file_storage->create_file_from_storedfile()
    line 709 of \lib\upgradelib.php: call to xmldb_format_grid_upgrade()
    line 1935 of \lib\upgradelib.php: call to upgrade_plugins()
    line 719 of \admin\index.php: call to upgrade_noncore()

**Comment by rimacher** [comment]
Linux 3.10.0-1160.59.1.el7.x86_64
mariadb (5.5.5-10.5.16-MariaDB-log)

**Comment by rimacher** [comment]
It now works, thank you.

**Comment by gjb2048** [comment]
@rimacher Thank you for letting me know.
